version: "3.8"

services:
    app:
        build: ./app
        restart: always
        ports:
            - 80:8080
    api:
        build: ./api
        restart: always
        ports:
            - 3000:3000
        env_file:
            - ./api/.env

